### PR TITLE
Instagram hack Create SECURITY.md .com

### PR DESCRIPTION
**Pull request by Srujansru**
Instagram hacking

### CODE REVIEW

**Comment by Srujansru** [comment]
cmd

**Comment by Srujansru** [comment]
Instagram hacking is good

**Comment by Srujansru** [comment]
Your IP address : 122.172.85.129 (India) It has been restricted by our anti-spam security system.

**Review by Alejand473 — COMMENTED** [review]
https://www.instagram.com/rhos11

**Pull request closed without merging**
